-- MySQL Script generated by MySQL Workbench
-- Fri Jul  3 17:48:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ComicWorld
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ComicWorld
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ComicWorld` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ComicWorld` ;

-- -----------------------------------------------------
-- Table `ComicWorld`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`StatusTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`StatusTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`ComicTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`ComicTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`Comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`Comics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `numOfChap` INT NOT NULL,
  `numOfView` INT NOT NULL,
  `source` MEDIUMTEXT NOT NULL,
  `image` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `Authors_id` INT NOT NULL,
  `StatusTypes_id` INT NOT NULL,
  `ComicTypes_id` INT NOT NULL,
  `Types_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Authors_id`, `StatusTypes_id`, `ComicTypes_id`, `Types_id`),
  INDEX `fk_Comics_Authors_idx` (`Authors_id` ASC) VISIBLE,
  INDEX `fk_Comics_StatusTypes1_idx` (`StatusTypes_id` ASC) VISIBLE,
  INDEX `fk_Comics_ComicTypes1_idx` (`ComicTypes_id` ASC) VISIBLE,
  INDEX `fk_Comics_Types1_idx` (`Types_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comics_Authors`
    FOREIGN KEY (`Authors_id`)
    REFERENCES `ComicWorld`.`Authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comics_StatusTypes1`
    FOREIGN KEY (`StatusTypes_id`)
    REFERENCES `ComicWorld`.`StatusTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comics_ComicTypes1`
    FOREIGN KEY (`ComicTypes_id`)
    REFERENCES `ComicWorld`.`ComicTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comics_Types1`
    FOREIGN KEY (`Types_id`)
    REFERENCES `ComicWorld`.`Types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`Chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`Chapters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `Comics_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Comics_id`),
  INDEX `fk_Chapters_Comics1_idx` (`Comics_id` ASC) VISIBLE,
  CONSTRAINT `fk_Chapters_Comics1`
    FOREIGN KEY (`Comics_id`)
    REFERENCES `ComicWorld`.`Comics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
