-- MySQL Script generated by MySQL Workbench
-- Sun Jul 12 09:09:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ComicWorld
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ComicWorld
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `ComicWorld` DEFAULT CHARACTER SET utf8mb4 ;
USE `ComicWorld` ;

-- -----------------------------------------------------
-- Table `ComicWorld`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`status_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`status_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`comic_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`comic_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `href` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`comics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `href` TINYTEXT NOT NULL,
  `description` LONGTEXT NULL,
  `numOfChaps` INT NULL,
  `numOfViews` INT NULL,
  `source` TINYTEXT NULL,
  `image` TINYTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `authors_id` INT NOT NULL,
  `types_id` INT NULL,
  `status_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comics_authors_idx` (`authors_id`),
  INDEX `fk_comics_types1_idx` (`types_id`),
  INDEX `fk_comics_status_types1_idx` (`status_types_id`),
  CONSTRAINT `fk_comics_authors`
    FOREIGN KEY (`authors_id`)
    REFERENCES `ComicWorld`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comics_types1`
    FOREIGN KEY (`types_id`)
    REFERENCES `ComicWorld`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comics_status_types1`
    FOREIGN KEY (`status_types_id`)
    REFERENCES `ComicWorld`.`status_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`chapters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `comics_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chapters_comics1_idx` (`comics_id`),
  CONSTRAINT `fk_chapters_comics1`
    FOREIGN KEY (`comics_id`)
    REFERENCES `ComicWorld`.`comics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComicWorld`.`comic_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComicWorld`.`comic_detail` (
  `comics_id` INT NOT NULL,
  `comic_types_id` INT NOT NULL,
  PRIMARY KEY (`comics_id`, `comic_types_id`),
  INDEX `fk_comics_has_comic_types_comic_types1_idx` (`comic_types_id`),
  INDEX `fk_comics_has_comic_types_comics1_idx` (`comics_id`),
  CONSTRAINT `fk_comics_has_comic_types_comics1`
    FOREIGN KEY (`comics_id`)
    REFERENCES `ComicWorld`.`comics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comics_has_comic_types_comic_types1`
    FOREIGN KEY (`comic_types_id`)
    REFERENCES `ComicWorld`.`comic_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
